git hub action calculator app
name: Calculator App Tests
on:
  push:
    branches: [main,develop]
  pull_request:
    branches: [main]

jobs:
  test:
    rums-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Step 4: Run tests
    - name: Run calculator tests
      run: python -m unittest test_calculator.py -v
    
    # Step 5: Run calculator app
    - name: Run calculator
      run: python calculator.py     